#define TEMP_PIN            A0
#define ULTRASOUND_PIN      2
#define HEATING_PIN         3
#define COOLING_PIN         4
#define DECODE_FLAG         0x01
#define TREAD_FLAG          0x02
#define TMONITOR_FLAG       0x04
#define STATUS_FLAG         0x08
#define END_OF_TEST_FLAG    0x10
#define FT5206_WAKE 11
#define FT5206_INT   48  
